version: '3'
services:
  webserver-practice:
    build: .
    image: webserver-practice
    ports:
    - "5000:5000"
    # - "5010:5010"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - .:/app
    container_name: webserver-practice
    # command: >
      # bash -c "python webserver.py"